apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lookup-hpa
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lookup-server
  targetCPUUtilizationPercentage: 70